/**
 * Writes out/sw.js after `next build`.
 *
 * The precache list has to be generated rather than hand-written, because Next
 * emits content-hashed filenames that change every build. The same hash is
 * embedded in the cache name, so any deploy produces a byte-different sw.js,
 * which is what triggers the browser to install the new version.
 *
 * This restores the offline capability the old single-file build had.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

const OUT = join(import.meta.dirname, '..', 'out');

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((e) => {
      const full = join(dir, e.name);
      return e.isDirectory() ? walk(full) : Promise.resolve([full]);
    }),
  );
  return files.flat();
}

const files = (await walk(OUT)).filter((f) => !f.endsWith(`${sep}sw.js`));

const hash = createHash('sha256');
const assets = [];
for (const f of files.sort()) {
  const url = '/' + relative(OUT, f).split(sep).join('/');
  assets.push(url);
  hash.update(url);
  hash.update(await readFile(f));
}
const version = hash.digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/generate-sw.mjs — do not edit. */
const CACHE = 'checklist-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

/** Serve from cache, then refresh the entry in the background. */
function staleWhileRevalidate(request, key) {
  return caches.open(CACHE).then((cache) =>
    cache.match(key).then((cached) => {
      const network = fetch(request)
        .then((response) => {
          if (response && response.ok) cache.put(key, response.clone());
          return response;
        })
        .catch(() => cached);
      return cached || network;
    }),
  );
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Every route renders the same shell, so navigations resolve to index.html.
  if (request.mode === 'navigate') {
    event.respondWith(staleWhileRevalidate(request, '/index.html'));
    return;
  }

  // Build output is content-hashed, so a hit can be served straight from cache.
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith(
      caches.match(request).then((cached) => cached || fetch(request)),
    );
    return;
  }

  event.respondWith(staleWhileRevalidate(request, request));
});
`;

await writeFile(join(OUT, 'sw.js'), sw);
console.log(`out/sw.js  ${assets.length} assets precached  cache=checklist-${version}`);
